trigger:
- main

pool:
  name: Local Agent

variables:
  OPENSHIFT_URL: '$(OPENSHIFT_URL)'   # Reemplaza con tu URL real
  OPENSHIFT_TOKEN: '$(OPENSHIFT_TOKEN)'          # Configura como variable secreta
  OPENSHIFT_NAMESPACE: '$(OPENSHIFT_NAMESPACE)'                 # Cambia si usas otro namespace

steps:
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '4.2'
    cmd: 'oc project jcalvo-dev'
  displayName: Switch to myapp project
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '4.2'
    cmd: 'oc new-app https://github.com/jmanuelcalvo/app.git'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '4.2'
    cmd: 'oc expose svc app'
    ignoreFlag: true
  displayName: Create route
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '4.2'
    cmd: 'oc start-build app --follow'
  displayName: Start new build
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '4.2'
    cmd: 'oc status'